-- ============================================================
-- IRISv2 - 02_iris_dw_dimensions.sql
-- Objectif : création des dimensions du Data Warehouse IRIS
-- Schéma   : iris_dw
-- ============================================================

-- ============================================================
-- 1. dim_date
-- Grain : 1 ligne par date calendrier
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_dw.dim_date (
    date_sk INTEGER PRIMARY KEY,          -- format YYYYMMDD, 0 = unknown
    date_val DATE UNIQUE,

    annee INTEGER,
    trimestre INTEGER,
    mois INTEGER,
    nom_mois TEXT,
    jour INTEGER,
    jour_semaine INTEGER,
    nom_jour_semaine TEXT,
    annee_mois TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT now()
);

COMMENT ON TABLE iris_dw.dim_date IS
'Dimension calendrier utilisée par les faits : sinistre, prime et inspection.';

INSERT INTO iris_dw.dim_date (
    date_sk, date_val, annee, trimestre, mois, nom_mois,
    jour, jour_semaine, nom_jour_semaine, annee_mois
)
VALUES (
    0, NULL, NULL, NULL, NULL, 'UNKNOWN',
    NULL, NULL, 'UNKNOWN', 'UNKNOWN'
)
ON CONFLICT (date_sk) DO NOTHING;


-- ============================================================
-- 2. dim_client
-- Source : Clients.xlsx
-- Grain  : 1 ligne par client CNAT + NUMPERS
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_dw.dim_client (
    client_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    client_natural_key TEXT NOT NULL UNIQUE,   -- CNAT|NUMPERS

    code_nature_client TEXT,                   -- CNAT
    num_client TEXT,                           -- NUMPERS

    type_identifiant TEXT,                     -- TYPEID
    identifiant_client TEXT,                   -- ID

    adresse TEXT,                              -- ADR1
    code_postal TEXT,                          -- CPOST
    localite_client TEXT,                      -- CITE
    gouvernorat_client TEXT,                   -- GOUVERNOR

    date_naissance DATE,                       -- DATE_NAISS
    sexe TEXT,                                 -- SEXE
    profession TEXT,                           -- PRF
    situation_familiale TEXT,                  -- SITUAFAMI
    nombre_enfants INTEGER,                    -- NBRENF

    date_debut_client DATE,                    -- DEBCNT

    source_system TEXT NOT NULL DEFAULT 'Clients.xlsx',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP
);

COMMENT ON TABLE iris_dw.dim_client IS
'Dimension client issue de Clients.xlsx. Grain : CNAT + NUMPERS.';

INSERT INTO iris_dw.dim_client (
    client_sk,
    client_natural_key,
    code_nature_client,
    num_client
)
VALUES (
    0,
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN'
)
ON CONFLICT (client_natural_key) DO NOTHING;


-- ============================================================
-- 3. dim_produit
-- Source : Production.xlsx / Sinistres.xlsx
-- Grain  : 1 ligne par produit / formule
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_dw.dim_produit (
    produit_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    produit_natural_key TEXT NOT NULL UNIQUE,  -- CODFAM|CODPROD|CODFORMU

    code_famille_produit TEXT,                 -- CODFAM
    code_produit TEXT,                         -- CODPROD
    libelle_produit TEXT,                      -- LIBPRDT
    code_formule TEXT,                         -- CODFORMU si disponible

    source_system TEXT NOT NULL DEFAULT 'Production.xlsx/Sinistres.xlsx',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP
);

COMMENT ON TABLE iris_dw.dim_produit IS
'Dimension produit / formule assurance.';

INSERT INTO iris_dw.dim_produit (
    produit_sk,
    produit_natural_key,
    code_produit,
    libelle_produit
)
VALUES (
    0,
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN'
)
ON CONFLICT (produit_natural_key) DO NOTHING;


-- ============================================================
-- 4. dim_garantie
-- Source : Sinistres.xlsx
-- Grain  : 1 ligne par garantie
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_dw.dim_garantie (
    garantie_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    garantie_natural_key TEXT NOT NULL UNIQUE, -- GRNTSINI

    code_garantie TEXT NOT NULL,
    libelle_garantie TEXT,
    famille_garantie TEXT,

    source_system TEXT NOT NULL DEFAULT 'Sinistres.xlsx',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP
);

COMMENT ON TABLE iris_dw.dim_garantie IS
'Dimension garantie issue de Sinistres.xlsx.';

INSERT INTO iris_dw.dim_garantie (
    garantie_sk,
    garantie_natural_key,
    code_garantie,
    libelle_garantie
)
VALUES (
    0,
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN'
)
ON CONFLICT (garantie_natural_key) DO NOTHING;


-- ============================================================
-- 5. dim_cause_sinistre
-- Source : Sinistres.xlsx
-- Grain  : 1 ligne par CAUSESINI + NATSINI + SOUNATSIN
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_dw.dim_cause_sinistre (
    cause_sinistre_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cause_sinistre_natural_key TEXT NOT NULL UNIQUE,

    code_cause_sinistre TEXT,                  -- CAUSESINI
    code_nature_sinistre TEXT,                 -- NATSINI
    code_sous_nature_sinistre TEXT,            -- SOUNATSIN

    libelle_cause_sinistre TEXT,
    libelle_nature_sinistre TEXT,
    libelle_sous_nature_sinistre TEXT,

    is_vol BOOLEAN NOT NULL DEFAULT false,
    is_vol_avec_retrouvaille BOOLEAN NOT NULL DEFAULT false,

    source_system TEXT NOT NULL DEFAULT 'Sinistres.xlsx',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP
);

COMMENT ON TABLE iris_dw.dim_cause_sinistre IS
'Typologie du sinistre : cause, nature et sous-nature.';

INSERT INTO iris_dw.dim_cause_sinistre (
    cause_sinistre_sk,
    cause_sinistre_natural_key,
    code_cause_sinistre,
    code_nature_sinistre,
    code_sous_nature_sinistre
)
VALUES (
    0,
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN'
)
ON CONFLICT (cause_sinistre_natural_key) DO NOTHING;


-- ============================================================
-- 6. dim_delegation
-- Source : Production.xlsx / Sinistres.xlsx
-- Grain  : 1 ligne par délégation
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_dw.dim_delegation (
    delegation_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    delegation_natural_key TEXT NOT NULL UNIQUE, -- IDDELEGA

    code_delegation TEXT NOT NULL,
    libelle_delegation TEXT,

    source_system TEXT NOT NULL DEFAULT 'Production.xlsx/Sinistres.xlsx',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP
);

COMMENT ON TABLE iris_dw.dim_delegation IS
'Dimension délégation / entité de gestion.';

INSERT INTO iris_dw.dim_delegation (
    delegation_sk,
    delegation_natural_key,
    code_delegation,
    libelle_delegation
)
VALUES (
    0,
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN'
)
ON CONFLICT (delegation_natural_key) DO NOTHING;


-- ============================================================
-- 7. dim_intermediaire
-- Source : Production.xlsx / Sinistres.xlsx
-- Grain  : 1 ligne par NATINT + IDINT
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_dw.dim_intermediaire (
    intermediaire_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    intermediaire_natural_key TEXT NOT NULL UNIQUE, -- NATINT|IDINT

    code_nature_intermediaire TEXT,                 -- NATINT
    code_intermediaire TEXT,                        -- IDINT
    nom_intermediaire TEXT,
    type_intermediaire TEXT,

    source_system TEXT NOT NULL DEFAULT 'Production.xlsx/Sinistres.xlsx',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP
);

COMMENT ON TABLE iris_dw.dim_intermediaire IS
'Dimension intermédiaire, agence ou courtier. Grain : NATINT + IDINT.';

INSERT INTO iris_dw.dim_intermediaire (
    intermediaire_sk,
    intermediaire_natural_key,
    code_nature_intermediaire,
    code_intermediaire
)
VALUES (
    0,
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN'
)
ON CONFLICT (intermediaire_natural_key) DO NOTHING;


-- ============================================================
-- 8. dim_vehicule
-- Source : Sinistres.xlsx / Production.xlsx / FicheVoitureStafim.xlsx
-- Grain  : 1 ligne par véhicule identifié
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_dw.dim_vehicule (
    vehicule_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vehicule_natural_key TEXT NOT NULL UNIQUE,  -- immatriculation normalisée ou VIN si disponible

    immatriculation TEXT,
    vin TEXT,

    marque TEXT,
    modele TEXT,
    genre_vehicule TEXT,
    usage_vehicule TEXT,
    energie TEXT,
    puissance TEXT,
    date_mise_circulation DATE,

    motorisation TEXT,

    source_system TEXT NOT NULL DEFAULT 'Sinistres.xlsx/Production.xlsx/FicheVoitureStafim.xlsx',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP
);

COMMENT ON TABLE iris_dw.dim_vehicule IS
'Dimension véhicule issue des sources sinistres, production et inspections Stafim.';

INSERT INTO iris_dw.dim_vehicule (
    vehicule_sk,
    vehicule_natural_key,
    immatriculation,
    vin
)
VALUES (
    0,
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN'
)
ON CONFLICT (vehicule_natural_key) DO NOTHING;


-- ============================================================
-- 9. dim_contrat
-- Source : Production.xlsx / Sinistres.xlsx
-- Grain  : 1 ligne par NUMCNT + NUMAVT + NUMMAJ
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_dw.dim_contrat (
    contrat_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    contrat_natural_key TEXT NOT NULL UNIQUE, -- NUMCNT|NUMAVT|NUMMAJ

    num_contrat TEXT NOT NULL,
    num_avenant TEXT,
    num_mise_a_jour TEXT,

    produit_sk BIGINT NOT NULL DEFAULT 0,
    intermediaire_sk BIGINT NOT NULL DEFAULT 0,
    delegation_sk BIGINT NOT NULL DEFAULT 0,

    date_debut_contrat DATE,                  -- DEBCNT
    date_fin_contrat DATE,                    -- FINCNT
    date_debut_effet DATE,                    -- DEBEFFET
    date_fin_effet DATE,                      -- FINEFFET

    duree_contrat TEXT,
    situation_contrat TEXT,                   -- SITUAT
    type_resiliation TEXT,                    -- TYPERESIL
    libelle_resiliation TEXT,                 -- LIB_RESIL

    coassurance TEXT,

    source_system TEXT NOT NULL DEFAULT 'Production.xlsx/Sinistres.xlsx',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP,

    CONSTRAINT fk_dim_contrat_produit
        FOREIGN KEY (produit_sk)
        REFERENCES iris_dw.dim_produit(produit_sk),

    CONSTRAINT fk_dim_contrat_intermediaire
        FOREIGN KEY (intermediaire_sk)
        REFERENCES iris_dw.dim_intermediaire(intermediaire_sk),

    CONSTRAINT fk_dim_contrat_delegation
        FOREIGN KEY (delegation_sk)
        REFERENCES iris_dw.dim_delegation(delegation_sk)
);

COMMENT ON TABLE iris_dw.dim_contrat IS
'Dimension contrat. Grain : NUMCNT + NUMAVT + NUMMAJ.';

INSERT INTO iris_dw.dim_contrat (
    contrat_sk,
    contrat_natural_key,
    num_contrat,
    num_avenant,
    num_mise_a_jour,
    produit_sk,
    intermediaire_sk,
    delegation_sk
)
VALUES (
    0,
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN',
    0,
    0,
    0
)
ON CONFLICT (contrat_natural_key) DO NOTHING;


-- ============================================================
-- 10. dim_checkpoint
-- Source : FicheVoitureStafim.xlsx / référentiel VHS
-- Grain  : 1 ligne par checkpoint Stafim
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_dw.dim_checkpoint (
    checkpoint_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    checkpoint_natural_key TEXT NOT NULL UNIQUE,

    checkpoint_code TEXT NOT NULL,
    checkpoint_label TEXT NOT NULL,
    checkpoint_category TEXT,

    tier TEXT,                                -- T1, T2, AP, etc.
    is_vhs_scored BOOLEAN NOT NULL DEFAULT true,

    is_vital BOOLEAN NOT NULL DEFAULT false,
    is_important BOOLEAN NOT NULL DEFAULT false,
    is_immobilizing BOOLEAN NOT NULL DEFAULT false,
    is_t2_critical BOOLEAN NOT NULL DEFAULT false,

    penalty_worn NUMERIC(10,2) NOT NULL DEFAULT 0,
    penalty_broken NUMERIC(10,2) NOT NULL DEFAULT 0,

    is_active BOOLEAN NOT NULL DEFAULT true,

    source_system TEXT NOT NULL DEFAULT 'FicheVoitureStafim.xlsx',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP
);

COMMENT ON TABLE iris_dw.dim_checkpoint IS
'Référentiel des checkpoints Stafim utilisés pour les inspections et le score VHS.';

INSERT INTO iris_dw.dim_checkpoint (
    checkpoint_sk,
    checkpoint_natural_key,
    checkpoint_code,
    checkpoint_label,
    tier,
    is_vhs_scored
)
VALUES (
    0,
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN',
    false
)
ON CONFLICT (checkpoint_natural_key) DO NOTHING;