-- ============================================================
-- IRISv2 - 03_iris_dw_facts.sql
-- Objectif : création des faits métier du Data Warehouse IRIS
-- Schéma   : iris_dw
-- ============================================================

-- ============================================================
-- 1. fact_prime
-- Source : Production.xlsx
-- Grain  : 1 ligne par contrat × avenant × mise à jour
-- Clé source : NUMCNT + NUMAVT + NUMMAJ
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_dw.fact_prime (
    prime_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    prime_natural_key TEXT NOT NULL UNIQUE, -- NUMCNT|NUMAVT|NUMMAJ

    client_sk BIGINT NOT NULL DEFAULT 0,
    contrat_sk BIGINT NOT NULL DEFAULT 0,
    vehicule_sk BIGINT NOT NULL DEFAULT 0,
    produit_sk BIGINT NOT NULL DEFAULT 0,
    intermediaire_sk BIGINT NOT NULL DEFAULT 0,
    delegation_sk BIGINT NOT NULL DEFAULT 0,

    date_debut_contrat_sk INTEGER NOT NULL DEFAULT 0,
    date_fin_contrat_sk INTEGER NOT NULL DEFAULT 0,
    date_debut_effet_sk INTEGER NOT NULL DEFAULT 0,
    date_fin_effet_sk INTEGER NOT NULL DEFAULT 0,

    total_prime NUMERIC(18,3),

    source_system TEXT NOT NULL DEFAULT 'Production.xlsx',
    etl_run_id TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT fk_fact_prime_client
        FOREIGN KEY (client_sk) REFERENCES iris_dw.dim_client(client_sk),

    CONSTRAINT fk_fact_prime_contrat
        FOREIGN KEY (contrat_sk) REFERENCES iris_dw.dim_contrat(contrat_sk),

    CONSTRAINT fk_fact_prime_vehicule
        FOREIGN KEY (vehicule_sk) REFERENCES iris_dw.dim_vehicule(vehicule_sk),

    CONSTRAINT fk_fact_prime_produit
        FOREIGN KEY (produit_sk) REFERENCES iris_dw.dim_produit(produit_sk),

    CONSTRAINT fk_fact_prime_intermediaire
        FOREIGN KEY (intermediaire_sk) REFERENCES iris_dw.dim_intermediaire(intermediaire_sk),

    CONSTRAINT fk_fact_prime_delegation
        FOREIGN KEY (delegation_sk) REFERENCES iris_dw.dim_delegation(delegation_sk),

    CONSTRAINT fk_fact_prime_date_debut_contrat
        FOREIGN KEY (date_debut_contrat_sk) REFERENCES iris_dw.dim_date(date_sk),

    CONSTRAINT fk_fact_prime_date_fin_contrat
        FOREIGN KEY (date_fin_contrat_sk) REFERENCES iris_dw.dim_date(date_sk),

    CONSTRAINT fk_fact_prime_date_debut_effet
        FOREIGN KEY (date_debut_effet_sk) REFERENCES iris_dw.dim_date(date_sk),

    CONSTRAINT fk_fact_prime_date_fin_effet
        FOREIGN KEY (date_fin_effet_sk) REFERENCES iris_dw.dim_date(date_sk),

    CONSTRAINT fk_fact_prime_etl_run
        FOREIGN KEY (etl_run_id) REFERENCES iris_admin.etl_run(etl_run_id)
);

COMMENT ON TABLE iris_dw.fact_prime IS
'Fait prime / production. Grain : NUMCNT + NUMAVT + NUMMAJ.';


-- ============================================================
-- 2. fact_sinistre
-- Source : Sinistres.xlsx
-- Grain  : 1 ligne par sinistre × garantie
-- Clé source : NUMSNT + GRNTSINI
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_dw.fact_sinistre (
    sinistre_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sinistre_natural_key TEXT NOT NULL UNIQUE, -- NUMSNT|GRNTSINI

    num_sinistre TEXT NOT NULL,

    client_sk BIGINT NOT NULL DEFAULT 0,
    contrat_sk BIGINT NOT NULL DEFAULT 0,
    vehicule_sk BIGINT NOT NULL DEFAULT 0,
    produit_sk BIGINT NOT NULL DEFAULT 0,
    garantie_sk BIGINT NOT NULL DEFAULT 0,
    intermediaire_sk BIGINT NOT NULL DEFAULT 0,
    delegation_sk BIGINT NOT NULL DEFAULT 0,
    cause_sinistre_sk BIGINT NOT NULL DEFAULT 0,

    date_survenance_sk INTEGER NOT NULL DEFAULT 0,
    date_declaration_sk INTEGER NOT NULL DEFAULT 0,
    date_ouverture_sk INTEGER NOT NULL DEFAULT 0,
    date_cloture_sk INTEGER NOT NULL DEFAULT 0,
    date_debut_effet_sk INTEGER NOT NULL DEFAULT 0,
    date_fin_effet_sk INTEGER NOT NULL DEFAULT 0,

    numero_risque TEXT,               -- NUMRISQ
    code_etat_sinistre TEXT,          -- CODE_ETAT
    etat_garantie TEXT,               -- ETATGRNT
    motif_cloture TEXT,               -- MOTIFCLOT

    montant_evaluation_initiale NUMERIC(18,3), -- EVAL_INIT
    montant_provision NUMERIC(18,3),            -- MNTPROVIS
    montant_paye_garantie NUMERIC(18,3),        -- MNTPAIGRN
    montant_declare NUMERIC(18,3),              -- MNTDECLAR
    montant_prevision NUMERIC(18,3),            -- MNTPREVIS
    montant_recours NUMERIC(18,3),              -- MNTRECOUR
    montant_total NUMERIC(18,3),                -- MNTTOTAL
    montant_total_net NUMERIC(18,3),            -- MNTTOTNET

    delai_declaration_jours INTEGER,
    delai_ouverture_jours INTEGER,
    anciennete_contrat_jours INTEGER,

    is_declaration_antidatee BOOLEAN NOT NULL DEFAULT false,
    is_declaration_tardive BOOLEAN NOT NULL DEFAULT false,
    is_sinistre_avant_contrat BOOLEAN NOT NULL DEFAULT false,
    is_sinistre_precoce BOOLEAN NOT NULL DEFAULT false,

    source_system TEXT NOT NULL DEFAULT 'Sinistres.xlsx',
    etl_run_id TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT fk_fact_sinistre_client
        FOREIGN KEY (client_sk) REFERENCES iris_dw.dim_client(client_sk),

    CONSTRAINT fk_fact_sinistre_contrat
        FOREIGN KEY (contrat_sk) REFERENCES iris_dw.dim_contrat(contrat_sk),

    CONSTRAINT fk_fact_sinistre_vehicule
        FOREIGN KEY (vehicule_sk) REFERENCES iris_dw.dim_vehicule(vehicule_sk),

    CONSTRAINT fk_fact_sinistre_produit
        FOREIGN KEY (produit_sk) REFERENCES iris_dw.dim_produit(produit_sk),

    CONSTRAINT fk_fact_sinistre_garantie
        FOREIGN KEY (garantie_sk) REFERENCES iris_dw.dim_garantie(garantie_sk),

    CONSTRAINT fk_fact_sinistre_intermediaire
        FOREIGN KEY (intermediaire_sk) REFERENCES iris_dw.dim_intermediaire(intermediaire_sk),

    CONSTRAINT fk_fact_sinistre_delegation
        FOREIGN KEY (delegation_sk) REFERENCES iris_dw.dim_delegation(delegation_sk),

    CONSTRAINT fk_fact_sinistre_cause
        FOREIGN KEY (cause_sinistre_sk) REFERENCES iris_dw.dim_cause_sinistre(cause_sinistre_sk),

    CONSTRAINT fk_fact_sinistre_date_survenance
        FOREIGN KEY (date_survenance_sk) REFERENCES iris_dw.dim_date(date_sk),

    CONSTRAINT fk_fact_sinistre_date_declaration
        FOREIGN KEY (date_declaration_sk) REFERENCES iris_dw.dim_date(date_sk),

    CONSTRAINT fk_fact_sinistre_date_ouverture
        FOREIGN KEY (date_ouverture_sk) REFERENCES iris_dw.dim_date(date_sk),

    CONSTRAINT fk_fact_sinistre_date_cloture
        FOREIGN KEY (date_cloture_sk) REFERENCES iris_dw.dim_date(date_sk),

    CONSTRAINT fk_fact_sinistre_date_debut_effet
        FOREIGN KEY (date_debut_effet_sk) REFERENCES iris_dw.dim_date(date_sk),

    CONSTRAINT fk_fact_sinistre_date_fin_effet
        FOREIGN KEY (date_fin_effet_sk) REFERENCES iris_dw.dim_date(date_sk),

    CONSTRAINT fk_fact_sinistre_etl_run
        FOREIGN KEY (etl_run_id) REFERENCES iris_admin.etl_run(etl_run_id)
);

COMMENT ON TABLE iris_dw.fact_sinistre IS
'Fait central sinistre. Grain : 1 ligne par sinistre × garantie.';


-- ============================================================
-- 3. fact_inspection
-- Source : FicheVoitureStafim.xlsx
-- Grain  : 1 ligne par inspection véhicule Stafim
-- Clé source : immatriculation + date + commande travaux
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_dw.fact_inspection (
    inspection_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    inspection_natural_key TEXT NOT NULL UNIQUE,

    vehicule_sk BIGINT NOT NULL DEFAULT 0,
    date_inspection_sk INTEGER NOT NULL DEFAULT 0,

    commande_travaux TEXT,
    heure_entree TEXT,

    agent_name TEXT,
    nom_prenom_client TEXT,
    telephone TEXT,

    immatriculation_source TEXT,
    vin_source TEXT,

    kilometrage INTEGER,
    motorisation TEXT,

    source_system TEXT NOT NULL DEFAULT 'FicheVoitureStafim.xlsx',
    etl_run_id TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT fk_fact_inspection_vehicule
        FOREIGN KEY (vehicule_sk) REFERENCES iris_dw.dim_vehicule(vehicule_sk),

    CONSTRAINT fk_fact_inspection_date
        FOREIGN KEY (date_inspection_sk) REFERENCES iris_dw.dim_date(date_sk),

    CONSTRAINT fk_fact_inspection_etl_run
        FOREIGN KEY (etl_run_id) REFERENCES iris_admin.etl_run(etl_run_id)
);

COMMENT ON TABLE iris_dw.fact_inspection IS
'Fait inspection véhicule Stafim. Grain : immatriculation + date + commande travaux.';


-- ============================================================
-- 4. fact_inspection_checkpoint
-- Source : FicheVoitureStafim.xlsx
-- Grain  : 1 ligne par inspection × checkpoint
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_dw.fact_inspection_checkpoint (
    inspection_checkpoint_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    inspection_sk BIGINT NOT NULL,
    checkpoint_sk BIGINT NOT NULL,

    statut_code TEXT,
    statut_libelle TEXT,
    enc_valeur NUMERIC(10,3),

    source_column_name TEXT,

    source_system TEXT NOT NULL DEFAULT 'FicheVoitureStafim.xlsx',
    etl_run_id TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT uq_fact_inspection_checkpoint
        UNIQUE (inspection_sk, checkpoint_sk),

    CONSTRAINT fk_fact_inspection_checkpoint_inspection
        FOREIGN KEY (inspection_sk) REFERENCES iris_dw.fact_inspection(inspection_sk),

    CONSTRAINT fk_fact_inspection_checkpoint_checkpoint
        FOREIGN KEY (checkpoint_sk) REFERENCES iris_dw.dim_checkpoint(checkpoint_sk),

    CONSTRAINT fk_fact_inspection_checkpoint_etl_run
        FOREIGN KEY (etl_run_id) REFERENCES iris_admin.etl_run(etl_run_id)
);

COMMENT ON TABLE iris_dw.fact_inspection_checkpoint IS
'Détail des checkpoints par inspection. Grain : inspection × checkpoint.';


-- ============================================================
-- Index utiles pour jointures DW / ERD / performances BI
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_fact_sinistre_client_sk
    ON iris_dw.fact_sinistre(client_sk);

CREATE INDEX IF NOT EXISTS idx_fact_sinistre_contrat_sk
    ON iris_dw.fact_sinistre(contrat_sk);

CREATE INDEX IF NOT EXISTS idx_fact_sinistre_vehicule_sk
    ON iris_dw.fact_sinistre(vehicule_sk);

CREATE INDEX IF NOT EXISTS idx_fact_sinistre_garantie_sk
    ON iris_dw.fact_sinistre(garantie_sk);

CREATE INDEX IF NOT EXISTS idx_fact_sinistre_cause_sk
    ON iris_dw.fact_sinistre(cause_sinistre_sk);

CREATE INDEX IF NOT EXISTS idx_fact_prime_contrat_sk
    ON iris_dw.fact_prime(contrat_sk);

CREATE INDEX IF NOT EXISTS idx_fact_prime_client_sk
    ON iris_dw.fact_prime(client_sk);

CREATE INDEX IF NOT EXISTS idx_fact_inspection_vehicule_sk
    ON iris_dw.fact_inspection(vehicule_sk);

CREATE INDEX IF NOT EXISTS idx_fact_inspection_checkpoint_inspection_sk
    ON iris_dw.fact_inspection_checkpoint(inspection_sk);

CREATE INDEX IF NOT EXISTS idx_fact_inspection_checkpoint_checkpoint_sk
    ON iris_dw.fact_inspection_checkpoint(checkpoint_sk);