-- ============================================================
-- IRISv2 - 04_iris_score.sql
-- Objectif : création des tables de scoring versionnées
-- Schéma   : iris_score
-- ============================================================


-- ============================================================
-- 1. scoring_run
-- Rôle : tracer chaque exécution de scoring FRAUD ou VHS
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_score.scoring_run (
    run_id TEXT PRIMARY KEY,

    run_type TEXT NOT NULL CHECK (run_type IN ('FRAUD', 'VHS')),
    run_version TEXT NOT NULL,

    started_at TIMESTAMP NOT NULL DEFAULT now(),
    ended_at TIMESTAMP,

    status TEXT NOT NULL CHECK (status IN ('STARTED', 'SUCCESS', 'FAILED', 'CANCELLED')),
    is_active BOOLEAN NOT NULL DEFAULT false,

    source_etl_run_id TEXT,

    rules_version TEXT,
    model_version TEXT,

    total_input INTEGER,
    total_scored INTEGER,

    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT fk_scoring_run_etl_run
        FOREIGN KEY (source_etl_run_id)
        REFERENCES iris_admin.etl_run(etl_run_id)
);

COMMENT ON TABLE iris_score.scoring_run IS
'Trace les exécutions de scoring FRAUD ou VHS. Un run actif est utilisé par iris_mart.';

CREATE UNIQUE INDEX IF NOT EXISTS uq_active_scoring_run
ON iris_score.scoring_run (run_type)
WHERE is_active = true;


-- ============================================================
-- 2. dim_fraud_rule
-- Rôle : référentiel des règles fraude
-- Grain : 1 ligne par règle fraude
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_score.dim_fraud_rule (
    rule_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    rule_code TEXT NOT NULL UNIQUE,
    rule_name TEXT NOT NULL,
    rule_description TEXT,
    rule_category TEXT,

    is_active BOOLEAN NOT NULL DEFAULT true,
    weight NUMERIC(10,4) NOT NULL DEFAULT 1.0,
    threshold_value TEXT,

    severity TEXT,
    requires_business_validation BOOLEAN NOT NULL DEFAULT false,

    rule_version TEXT NOT NULL DEFAULT 'v1',

    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP
);

COMMENT ON TABLE iris_score.dim_fraud_rule IS
'Référentiel des règles fraude utilisées dans le scoring rule-based.';


-- ============================================================
-- 3. fact_fraud_score
-- Rôle : résultat scoring fraude par sinistre et par run
-- Grain : 1 ligne par sinistre × garantie × run FRAUD
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_score.fact_fraud_score (
    fraud_score_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sinistre_sk BIGINT NOT NULL,
    run_id TEXT NOT NULL,

    score_rule NUMERIC(10,6),
    score_rule_norm NUMERIC(10,6),
    score_ml NUMERIC(10,6),
    score_cross NUMERIC(10,6),
    score_global NUMERIC(10,6),

    risk_level TEXT,
    confidence_level TEXT,

    rules_triggered_count INTEGER,

    scored_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT uq_fact_fraud_score
        UNIQUE (sinistre_sk, run_id),

    CONSTRAINT fk_fact_fraud_score_sinistre
        FOREIGN KEY (sinistre_sk)
        REFERENCES iris_dw.fact_sinistre(sinistre_sk),

    CONSTRAINT fk_fact_fraud_score_run
        FOREIGN KEY (run_id)
        REFERENCES iris_score.scoring_run(run_id),

    CONSTRAINT ck_fact_fraud_score_risk_level
        CHECK (
            risk_level IS NULL
            OR risk_level IN ('NORMAL', 'FAIBLE', 'MOYEN', 'ELEVE')
        )
);

COMMENT ON TABLE iris_score.fact_fraud_score IS
'Score fraude hybride versionné. Grain : sinistre × garantie × run FRAUD.';


-- ============================================================
-- 4. fact_fraud_rule_detail
-- Rôle : explication des règles déclenchées
-- Grain : 1 ligne par score fraude × règle déclenchée
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_score.fact_fraud_rule_detail (
    fraud_rule_detail_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    fraud_score_sk BIGINT NOT NULL,
    sinistre_sk BIGINT NOT NULL,
    rule_sk BIGINT,
    rule_code TEXT NOT NULL,
    run_id TEXT NOT NULL,

    observed_value TEXT,
    threshold_value TEXT,
    rule_weight NUMERIC(10,4),
    rule_contribution NUMERIC(10,6),

    created_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT fk_fact_fraud_rule_detail_score
        FOREIGN KEY (fraud_score_sk)
        REFERENCES iris_score.fact_fraud_score(fraud_score_sk),

    CONSTRAINT fk_fact_fraud_rule_detail_sinistre
        FOREIGN KEY (sinistre_sk)
        REFERENCES iris_dw.fact_sinistre(sinistre_sk),

    CONSTRAINT fk_fact_fraud_rule_detail_rule
        FOREIGN KEY (rule_sk)
        REFERENCES iris_score.dim_fraud_rule(rule_sk),

    CONSTRAINT fk_fact_fraud_rule_detail_run
        FOREIGN KEY (run_id)
        REFERENCES iris_score.scoring_run(run_id)

    CONSTRAINT uq_fraud_rule_detail
    UNIQUE (fraud_score_sk, rule_code)    
);

COMMENT ON TABLE iris_score.fact_fraud_rule_detail IS
'Détail des règles fraude déclenchées pour expliquer le score fraude.';


-- ============================================================
-- 5. fact_inspection_sinistre_cross
-- Rôle : rapprochement inspection Stafim / sinistre
-- Grain : 1 ligne par inspection × sinistre rapproché × run
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_score.fact_inspection_sinistre_cross (
    cross_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    inspection_sk BIGINT NOT NULL,
    sinistre_sk BIGINT NOT NULL,
    vehicule_sk BIGINT NOT NULL DEFAULT 0,
    run_id TEXT NOT NULL,

    delai_inspection_sinistre_jours INTEGER,

    flag_sinistre_post_inspection BOOLEAN NOT NULL DEFAULT false,
    flag_defaut_coherent_garantie BOOLEAN NOT NULL DEFAULT false,
    flag_t1_vers_rc BOOLEAN NOT NULL DEFAULT false,
    flag_multi_garanties BOOLEAN NOT NULL DEFAULT false,
    flag_avenant_post_inspection BOOLEAN NOT NULL DEFAULT false,

    score_cross NUMERIC(10,6),
    risk_level_cross TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT uq_fact_inspection_sinistre_cross
        UNIQUE (inspection_sk, sinistre_sk, run_id),

    CONSTRAINT fk_cross_inspection
        FOREIGN KEY (inspection_sk)
        REFERENCES iris_dw.fact_inspection(inspection_sk),

    CONSTRAINT fk_cross_sinistre
        FOREIGN KEY (sinistre_sk)
        REFERENCES iris_dw.fact_sinistre(sinistre_sk),

    CONSTRAINT fk_cross_vehicule
        FOREIGN KEY (vehicule_sk)
        REFERENCES iris_dw.dim_vehicule(vehicule_sk),

    CONSTRAINT fk_cross_run
        FOREIGN KEY (run_id)
        REFERENCES iris_score.scoring_run(run_id)
);

COMMENT ON TABLE iris_score.fact_inspection_sinistre_cross IS
'Rapprochement inspection-sinistre utilisé dans le score fraude cross.';


-- ============================================================
-- 6. fact_vhs_score
-- Rôle : résultat VHS par inspection et par run
-- Grain : 1 ligne par inspection × run VHS
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_score.fact_vhs_score (
    vhs_score_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    inspection_sk BIGINT NOT NULL,
    vehicule_sk BIGINT NOT NULL DEFAULT 0,
    run_id TEXT NOT NULL,

    vhs_score_raw NUMERIC(10,6),
    kilometrage_penalty NUMERIC(10,6),
    vhs_score_final NUMERIC(10,6),
    vhs_score_displayed NUMERIC(10,6),

    safety_score NUMERIC(10,6),
    functional_score NUMERIC(10,6),
    cosmetic_score NUMERIC(10,6),

    safety_grade TEXT,
    vhs_decision TEXT,
    is_drivable BOOLEAN,

    scored_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT uq_fact_vhs_score
        UNIQUE (inspection_sk, run_id),

    CONSTRAINT fk_fact_vhs_score_inspection
        FOREIGN KEY (inspection_sk)
        REFERENCES iris_dw.fact_inspection(inspection_sk),

    CONSTRAINT fk_fact_vhs_score_vehicule
        FOREIGN KEY (vehicule_sk)
        REFERENCES iris_dw.dim_vehicule(vehicule_sk),

    CONSTRAINT fk_fact_vhs_score_run
        FOREIGN KEY (run_id)
        REFERENCES iris_score.scoring_run(run_id),

    CONSTRAINT ck_fact_vhs_grade
        CHECK (
            safety_grade IS NULL
            OR safety_grade IN ('A', 'B', 'C', 'D')
        )
);

COMMENT ON TABLE iris_score.fact_vhs_score IS
'Score VHS versionné. Grain : inspection × run VHS.';


-- ============================================================
-- 7. fact_vhs_penalty_detail
-- Rôle : détail des pénalités VHS appliquées
-- Grain : 1 ligne par inspection × checkpoint pénalisant × run
-- ============================================================

CREATE TABLE IF NOT EXISTS iris_score.fact_vhs_penalty_detail (
    vhs_penalty_detail_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vhs_score_sk BIGINT NOT NULL,
    inspection_sk BIGINT NOT NULL,
    checkpoint_sk BIGINT NOT NULL,
    vehicule_sk BIGINT NOT NULL DEFAULT 0,
    run_id TEXT NOT NULL,

    observed_value TEXT,
    penalty_applied NUMERIC(10,6),
    penalty_reason TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT fk_vhs_penalty_score
        FOREIGN KEY (vhs_score_sk)
        REFERENCES iris_score.fact_vhs_score(vhs_score_sk),

    CONSTRAINT fk_vhs_penalty_inspection
        FOREIGN KEY (inspection_sk)
        REFERENCES iris_dw.fact_inspection(inspection_sk),

    CONSTRAINT fk_vhs_penalty_checkpoint
        FOREIGN KEY (checkpoint_sk)
        REFERENCES iris_dw.dim_checkpoint(checkpoint_sk),

    CONSTRAINT fk_vhs_penalty_vehicule
        FOREIGN KEY (vehicule_sk)
        REFERENCES iris_dw.dim_vehicule(vehicule_sk),

    CONSTRAINT fk_vhs_penalty_run
        FOREIGN KEY (run_id)
        REFERENCES iris_score.scoring_run(run_id)
);

COMMENT ON TABLE iris_score.fact_vhs_penalty_detail IS
'Détail explicatif des pénalités VHS appliquées par checkpoint.';


-- ============================================================
-- Index utiles
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_fact_fraud_score_sinistre
    ON iris_score.fact_fraud_score(sinistre_sk);

CREATE INDEX IF NOT EXISTS idx_fact_fraud_score_run
    ON iris_score.fact_fraud_score(run_id);

CREATE INDEX IF NOT EXISTS idx_fact_fraud_rule_detail_score
    ON iris_score.fact_fraud_rule_detail(fraud_score_sk);

CREATE INDEX IF NOT EXISTS idx_fact_fraud_rule_detail_run
    ON iris_score.fact_fraud_rule_detail(run_id);

CREATE INDEX IF NOT EXISTS idx_cross_sinistre
    ON iris_score.fact_inspection_sinistre_cross(sinistre_sk);

CREATE INDEX IF NOT EXISTS idx_cross_inspection
    ON iris_score.fact_inspection_sinistre_cross(inspection_sk);

CREATE INDEX IF NOT EXISTS idx_fact_vhs_score_inspection
    ON iris_score.fact_vhs_score(inspection_sk);

CREATE INDEX IF NOT EXISTS idx_fact_vhs_score_run
    ON iris_score.fact_vhs_score(run_id);

CREATE INDEX IF NOT EXISTS idx_vhs_penalty_score
    ON iris_score.fact_vhs_penalty_detail(vhs_score_sk);

CREATE INDEX IF NOT EXISTS idx_vhs_penalty_checkpoint
    ON iris_score.fact_vhs_penalty_detail(checkpoint_sk);